### ISSUE TITLE
Give IVs for the whole family

### ISSUE THREAD

**Issue by Dexter192** [Dexter192/PoGoPvPBot#10]
If the user searches for +mudkip it should print the IVs for the whole family

**Comment by Dexter192** [comment]
@hrk can you briefly look over this evolution list? If it is complete/valid I will implement +searching for the bot. We can use either, .json or .csv
[evolutions.zip](https://github.com/Dexter192/PoGoPvPBot/files/3439246/evolutions.zip)

**Comment by hrk** [comment]
I think Alolan forms should be split from Kanto forms, as they usually have different stats.

**Comment by Dexter192** [comment]
Agreed. Also for Raichu? 
What is your opinion about csv and json?
