### ISSUE TITLE
Show worst combo percentage in /iv command

### ISSUE THREAD

**Issue by hrk** [Dexter192/PoGoPvPBot#4]
Currently:

> Your geodude is on rank 2329
> (A/D/S): 1 / 10 / 10
> CP: 1128
> Stat Product: 1203162
> Percent: 84.10%

Proposed:
> Your geodude is on rank 2329
> (A/D/S): 1 / 10 / 10
> CP: 1128
> Stat Product: 1203162
> Percent: 84.10% (Worst: 71,67%)

Please add an indication of the statprod of the worst combo (4096th) in order to easily assest the spread for that specific pokemon species and, thus, assest the viability of such pokemon.
Some pokemon have a huge spread (Geodude is a perfect example with a worst of 71.67% - ok, geodude sucks in PvP it's just an example) whereas other have a very small spread.

**Comment by Dexter192** [comment]
As far as I know Gostadium doesn't support retrieving the worst percentage. 
I want to clone their spreadsheets anyways to reduce the number of calls that I make to their website. Once that is done it should be easy

**Comment by hrk** [comment]
Some other examples of different spread, all of the following are 4096th combos:

Lucario: 90.09%
Venusaur: 90.21%

**Comment by hrk** [comment]
Oh, you're accessing GoStadium? I thought it was calculated on the fly. If you want I already made a generator for all the possible combinations and saved them as a csv file. It's done in Java, if I knew (read: liked) Python, I'd just pushed it to you so that you could store them in your db.

**Comment by Dexter192** [comment]
Thats exactly the plan. Compute csv files for each Pokemon and then just read them
